name: yakyak
summary: YakYak
description: |
 Desktop client for Google Hangouts
adopt-info: yakyak

grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  yakyak:
    plugin: nil
    override-build: |
      set -x
      snapcraftctl build
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        FILTER="x64"
      elif [ "$SNAPCRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then
        FILTER="ia32"
      else
        echo "ERROR! YakYak only produces debs for amd64 and i386. Failing the build here."
        exit 1
      fi
      # Get the latest releases json
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/yakyak/yakyak/releases -O releases.json
      # Get the version from the tag_name and the download URL.
      # lets get 1.5.3
      ##VERSION=$(jq . releases.json | grep tag_name | grep 1.5.3 | cut -d'"' -f4 | sed s'/v//' | head -n 1)
      ##TARBALL_URL=$(grep browser_download releases.json | grep "${VERSION}" | grep "${FILTER}.tar.gz" | cut -d'"' -f4)
      ##TARBALL=$(basename "${TARBALL_URL}")
      VERSION=1.5.3
      TARBALL_URL=https://github.com/yakyak/yakyak/releases/download/v1.5.3/yakyak-1.5.3-linux-x64.tar.gz
      TARBALL=yakyak-1.5.3-linux-x64.tar.gz
      echo "Downloading ${TARBALL_URL}..."
      wget --quiet "${TARBALL_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${TARBALL}"
      echo "Unpacking ${TARBALL}..."
      tar xf "${SNAPCRAFT_PART_INSTALL}/${TARBALL}" -C "${SNAPCRAFT_PART_INSTALL}/"
      mv "${SNAPCRAFT_PART_INSTALL}/yakyak-linux-${FILTER}" "${SNAPCRAFT_PART_INSTALL}/yakyak"
      # https://github.com/yakyak/yakyak/issues/918#issuecomment-389772323
      # sed -i 's|script>/gm|script( nonce="(\.\*\?)"\)\?>/gm|' "${SNAPCRAFT_PART_INSTALL}/yakyak/resources/app/node_modules/hangupsjs/lib/init.js"
      rm -f releases.json 2>/dev/null
      rm -f "${SNAPCRAFT_PART_INSTALL}/${TARBALL}" 2>/dev/null
      snapcraftctl set-version "$VERSION"
    after:
      - desktop-gtk3
    build-packages:
      - jq
      - sed
      - tar
      - wget
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  yakyak:
    command: bin/desktop-launch $SNAP/yakyak/yakyak
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR
      # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
      # are used and do not fall back to Notification Area applets
      # or disappear completely.
      XDG_CURRENT_DESKTOP: Unity
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - bluez
      - browser-support
      - camera
      - gsettings
      - home
      - mount-observe
      - network
      - network-observe
      - process-control
      - pulseaudio
      - screen-inhibit-control
      - system-observe
      - unity7
      - x11
